name: Apply the changes to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Patching the infrastructure
        env:
          K8S_CLUSTER_ID: ${{ secrets.K8S_CLUSTER_ID }}
          LARAVEL_APP_SECRET: ${{ secrets.LARAVEL_APP_SECRET }}
        run: |
          set -e

          # Installs the kubectl CLI tool.
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

          # Save the kubeconfig to connect our kubectl to our cluster.
          doctl kubernetes cluster kubeconfig save ${K8S_CLUSTER_ID}

          # Create the Laravel app secret file.
          echo "$LARAVEL_APP_SECRET" > .env

          # Deploy!
          ./deploy.sh

          # Clean up
          rm .env
